language: node_js
node_js:
  - "lts/*"

script: yarn run lint

cache:
  yarn: true
  directories:
    - "node_modules"

# use latest yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

# fix upath incompatibility
install: yarn --ignore-engines

# GitHub Pages deploy
before_deploy:
  - npm run predeploy

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: dist
    on:
      branch: master
